<?php

/**
 * Module: XoopsTube
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 *
 * PHP version 5
 *
 * @category        Module
 * @package         Xoopstube
 * @author          XOOPS Development Team
 * @copyright       2001-2013 The XOOPS Project
 * @license         GNU GPL 2 or later (http://www.gnu.org/licenses/gpl-2.0.html)
 * @version         $Id$
 * @link            http://sourceforge.net/projects/xoops/
 * @since           1.0.6
 */

$mydirname = basename(__DIR__);

$modversion['name']    = _MI_XOOPSTUBE_NAME;
$modversion['version'] = '1.06';
//$modversion['releasedate'] = 'June 19, 2012';
$modversion['status']      = 'Final';
$modversion['description'] = _MI_XOOPSTUBE_DESC;
//$modversion['license'] 		= _MI_XOOPSTUBE_LICENSEDSC;
$modversion['help']        = 'page=help';
$modversion['license']     = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html";
$modversion['official']    = 0;
$modversion['image']       = 'assets/images/xtube_slogo.png';

$modversion['iconsmall'] = 'assets/images/xtube_iconsmall.png';
$modversion['iconbig']   = 'assets/images/xtube_iconbig.png';
$modversion['dirname']   = $mydirname;
//$modversion['dirname'] 		= 'xoopstube';

$modversion['author']                 = "McDonald";
$modversion['credits']                = "WF-Projects Team. Based on the module WF-Links, thanks to the dream-team for some code snippits.";
$modversion['author_credits']         = _MI_XOOPSTUBE_AUTHOR_CREDITSTEXT;
$modversion['developer_website_url']  = "http://members.lycos.nl/mcdonaldsstore/";
$modversion['developer_website_name'] = "McDonalds Store";

$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses/moduleadmin';
$modversion['icons16']        = 'Frameworks/moduleclasses/icons/16';
$modversion['icons32']        = 'Frameworks/moduleclasses/icons/32';

//about
$modversion["module_status"]       = "RC 2";
$modversion['release_date']        = "2014/04/23";
$modversion['release_file']        = XOOPS_URL . "/modules/" . $modversion['dirname'] . "/docs/changelog.txt";
$modversion["module_website_url"]  = "www.xoops.org/";
$modversion["module_website_name"] = "XOOPS";
$modversion['min_php']             = '5.5';
$modversion['min_xoops']           = "2.5.7.2";
$modversion['min_admin']           = '1.1';
$modversion['min_db']              = array(
    'mysql'  => '5.0.7',
    'mysqli' => '5.0.7'
);

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
include_once 'include/config.php';
$modversion['tables'][0] = 'xoopstube_broken';
$modversion['tables'][1] = 'xoopstube_cat';
$modversion['tables'][2] = 'xoopstube_videos';
$modversion['tables'][3] = 'xoopstube_mod';
$modversion['tables'][4] = 'xoopstube_votedata';
$modversion['tables'][5] = 'xoopstube_indexpage';
$modversion['tables'][6] = 'xoopstube_altcat';

// Launch additional install script to check
// the existence of tables 'wf_resources_types' and 'wf_resources'
$modversion['onInstall'] = '';
$modversion['onUpdate']  = 'include/update.php';

// Admin things
$modversion['hasAdmin']    = 1;
$modversion['system_menu'] = 1;
$modversion['adminindex']  = 'admin/index.php';
$modversion['adminmenu']   = 'admin/menu.php';

// Blocks
$i = 0;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_top.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME1;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME1_DESC;
$modversion['blocks'][$i]['show_func']   = 'showTopVideoBlock';
$modversion['blocks'][$i]['edit_func']   = 'editTopVideoBlock';
$modversion['blocks'][$i]['options']     = 'published|10|19|d/m/Y|0';
$modversion['blocks'][$i]['template']    = 'xoopstube_block_new_t.tpl';
$modversion['blocks'][$i]['can_clone']   = true;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_top.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME2;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME2_DESC;
$modversion['blocks'][$i]['show_func']   = 'showTopVideoBlock';
$modversion['blocks'][$i]['edit_func']   = 'editTopVideoBlock';
$modversion['blocks'][$i]['options']     = 'published|10|19|d/m/Y|0';
$modversion['blocks'][$i]['template']    = 'xoopstube_block_new.tpl';
$modversion['blocks'][$i]['can_clone']   = true;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_top.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME3;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME3_DESC;
$modversion['blocks'][$i]['show_func']   = 'showTopVideoBlock';
$modversion['blocks'][$i]['edit_func']   = 'editTopVideoBlock';
$modversion['blocks'][$i]['options']     = 'hits|10|19|d/m/Y|0';
$modversion['blocks'][$i]['template']    = 'xoopstube_block_top_t.tpl';
$modversion['blocks'][$i]['can_clone']   = true;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_top.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME4;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME4_DESC;
$modversion['blocks'][$i]['show_func']   = 'showTopVideoBlock';
$modversion['blocks'][$i]['edit_func']   = 'editTopVideoBlock';
$modversion['blocks'][$i]['options']     = 'hits|10|19|d/m/Y|0';
$modversion['blocks'][$i]['template']    = 'xoopstube_block_top.tpl';
$modversion['blocks'][$i]['can_clone']   = true;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_top.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME5;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME5_DESC;
$modversion['blocks'][$i]['show_func']   = 'showTopVideoBlock';
$modversion['blocks'][$i]['edit_func']   = 'editTopVideoBlock';
$modversion['blocks'][$i]['options']     = 'published|5|19|d/m/Y|0';
$modversion['blocks'][$i]['template']    = 'xoopstube_block_new_h.tpl';
$modversion['blocks'][$i]['can_clone']   = true;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_top.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME6;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME6_DESC;
$modversion['blocks'][$i]['show_func']   = 'getRandomVideo';
$modversion['blocks'][$i]['edit_func']   = 'editTopVideoBlock';
$modversion['blocks'][$i]['options']     = 'random|5|19|d/m/Y|0';
$modversion['blocks'][$i]['template']    = 'xoopstube_block_random.tpl';
$modversion['blocks'][$i]['can_clone']   = true;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_top.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME7;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME7_DESC;
$modversion['blocks'][$i]['show_func']   = 'getRandomVideoForHorizontalBlock';
$modversion['blocks'][$i]['edit_func']   = 'editTopVideoBlock';
$modversion['blocks'][$i]['options']     = 'randomh|5|19|d/m/Y|0';
$modversion['blocks'][$i]['template']    = 'xoopstube_block_random_h.tpl';
$modversion['blocks'][$i]['can_clone']   = true;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_banner.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME8;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME8_DESC;
$modversion['blocks'][$i]['show_func']   = 'xtubeShowBannerB';
$modversion['blocks'][$i]['edit_func']   = 'xtubeEditBannerB';
$modversion['blocks'][$i]['options']     = 'hits|10|19';
$modversion['blocks'][$i]['template']    = 'xoopstube_block_banner.tpl';
$modversion['blocks'][$i]['can_clone']   = true;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_block_tag.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME9;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME9_DESC;
$modversion['blocks'][$i]['show_func']   = 'xtubeShowTagBlockCloud';
$modversion['blocks'][$i]['edit_func']   = 'xtubeEditTagBlockCloud';
$modversion['blocks'][$i]['options']     = '100|0|150|80';
$modversion['blocks'][$i]['template']    = 'xoopstube_tag_block_cloud.tpl';
$modversion['blocks'][$i]['can_clone']   = true;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_block_tag.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME10;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME10_DESC;
$modversion['blocks'][$i]['show_func']   = 'xtubeShowTagBlockTop';
$modversion['blocks'][$i]['edit_func']   = 'xtubeEditTagBlockTop';
$modversion['blocks'][$i]['options']     = '50|30|c';
$modversion['blocks'][$i]['template']    = 'xoopstube_tag_block_tag.tpl';
$modversion['blocks'][$i]['can_clone']   = true;
++$i;
$modversion['blocks'][$i]['file']        = $modversion['dirname'] . '_top.php';
$modversion['blocks'][$i]['name']        = _MI_XOOPSTUBE_BNAME11;
$modversion['blocks'][$i]['description'] = _MI_XOOPSTUBE_BNAME11_DESC;
$modversion['blocks'][$i]['show_func']   = "getSpotlightVideos";
$modversion['blocks'][$i]['edit_func']   = "editTopVideoBlock";
$modversion['blocks'][$i]['options']     = "date|3|19";
$modversion['blocks'][$i]['template']    = 'xoopstube_block_spotlight.tpl';
$modversion['blocks'][$i]['can_clone']   = true;

// Menu
$modversion['hasMain'] = 1;

// This part inserts the selected topics as sub items in the Xoops main menu
$module_handler = & xoops_gethandler('module');
$module         = & $module_handler->getByDirname($modversion['dirname']);
$cansubmit      = 0;
if (is_object($module)) {
    global $xoopsUser;
    $groups        = (is_object($xoopsUser)) ? $xoopsUser->getGroups() : XOOPS_GROUP_ANONYMOUS;
    $gperm_handler = & xoops_gethandler('groupperm');
    if ($gperm_handler->checkRight('XTubeSubPerm', 0, $groups, $module->getVar('mid'))) {
        $cansubmit = 1;
    }
}
if ($cansubmit == 1) {
    $modversion['sub'][0]['name'] = _MI_XOOPSTUBE_SMNAME1;
    $modversion['sub'][0]['url']  = 'submit.php';
}
unset($cansubmit);

$i                             = 1;
$modversion['sub'][$i]['name'] = _MI_XOOPSTUBE_SMNAME2;
$modversion['sub'][$i]['url']  = 'topten.php?list=hit';

++$i;
$modversion['sub'][$i]['name'] = _MI_XOOPSTUBE_SMNAME3;
$modversion['sub'][$i]['url']  = 'topten.php?list=rate';

++$i;
$modversion['sub'][$i]['name'] = _MI_XOOPSTUBE_SMNAME4;
$modversion['sub'][$i]['url']  = 'newlist.php?newvideoshowdays=7';
unset($i);

// Search
$modversion['hasSearch']      = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'xtubeSearch';

// Comments
$modversion['hasComments']             = 1;
$modversion['comments']['itemName']    = 'lid';
$modversion['comments']['pageName']    = 'singlevideo.php';
$modversion['comments']['extraParams'] = array('cid');

// Comment callback functions
$modversion['comments']['callbackFile']        = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'xtubeApproveComment';
$modversion['comments']['callback']['update']  = 'xtubeUpdateComment';

// Templates
$i = 0;
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_brokenvideo.tpl';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_videoload.tpl';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_index.tpl';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_ratevideo.tpl';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_singlevideo.tpl';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_topten.tpl';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_viewcat.tpl';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_newlistindex.tpl';
$modversion['templates'][$i]['description'] = '';

++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_common_letterschoice.tpl';
$modversion['templates'][$i]['description'] = '';

$i = 0;

// Module config setting
$i = 0;
++$i;
$modversion['config'][$i]['name']        = 'popular';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_POPULAR';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_POPULARDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 100;
$modversion['config'][$i]['options']     = array(
    '5'    => 5,
    '10'   => 10,
    '50'   => 50,
    '100'  => 100,
    '200'  => 200,
    '500'  => 500,
    '1000' => 1000
);
++$i;
$modversion['config'][$i]['name']        = 'displayicons';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_ICONDISPLAY';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_DISPLAYICONDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
$modversion['config'][$i]['options']     = array(
    '_MI_XOOPSTUBE_DISPLAYICON1' => 1,
    '_MI_XOOPSTUBE_DISPLAYICON2' => 2,
    '_MI_XOOPSTUBE_DISPLAYICON3' => 3
);
++$i;
$modversion['config'][$i]['name']        = 'daysnew';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_DAYSNEW';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_DAYSNEWDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 10;
++$i;
$modversion['config'][$i]['name']        = 'daysupdated';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_DAYSUPDATED';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_DAYSUPDATEDDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 10;
++$i;
$modversion['config'][$i]['name']        = 'perpage';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_PERPAGE';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_PERPAGEDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 10;
$modversion['config'][$i]['options']     = array(
    '5'  => 5,
    '10' => 10,
    '15' => 15,
    '20' => 20,
    '25' => 25,
    '30' => 30,
    '50' => 50
);
++$i;
$modversion['config'][$i]['name']        = 'admin_perpage';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_ADMINPAGE';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_AMDMINPAGEDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 10;
$modversion['config'][$i]['options']     = array(
    '5'   => 5,
    '10'  => 10,
    '15'  => 15,
    '20'  => 20,
    '25'  => 25,
    '30'  => 30,
    '50'  => 50,
    '75'  => 75,
    '100' => 100
);
++$i;
$qa                                      = ' (A)';
$qd                                      = ' (D)';
$modversion['config'][$i]['name']        = 'linkxorder';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_ARTICLESSORT';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_ARTICLESSORTDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'title ASC';
$modversion['config'][$i]['options']     = array(
    _MI_XOOPSTUBE_TITLE . $qa      => 'title ASC',
    _MI_XOOPSTUBE_TITLE . $qd      => 'title DESC',
    _MI_XOOPSTUBE_SUBMITTED2 . $qa => 'published ASC',
    _MI_XOOPSTUBE_SUBMITTED2 . $qd => 'published DESC',
    _MI_XOOPSTUBE_RATING . $qa     => 'rating ASC',
    _MI_XOOPSTUBE_RATING . $qd     => 'rating DESC',
    _MI_XOOPSTUBE_POPULARITY . $qa => 'hits ASC',
    _MI_XOOPSTUBE_POPULARITY . $qd => 'hits DESC'
);
++$i;
$modversion['config'][$i]['name']        = 'sortcats';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_SORTCATS';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_SORTCATSDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'title';
$modversion['config'][$i]['options']     = array(
    'Weight' => 'weight',
    'Title'  => 'title'
);
++$i;
$modversion['config'][$i]['name']        = 'subcats';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_SUBCATS';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_SUBCATSDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
++$i;
$modversion['config'][$i]['name']        = 'catcolumns';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_CATCOLUMNS';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_CATCOLUMNSDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 2;
$modversion['config'][$i]['options']     = array(
    '1' => 1,
    '2' => 2,
    '3' => 3,
    '4' => 4,
    '5' => 5
);

++$i;
xoops_load('XoopsEditorHandler');
$editor_handler = XoopsEditorHandler::getInstance();
$editorList     = array_flip($editor_handler->getList());

$modversion['config'][$i] = array(
    'name'        => 'form_options',
    'title'       => '_MI_XOOPSTUBE_EDITOR',
    'description' => '_MI_XOOPSTUBE_EDITORCHOICE',
    'formtype'    => 'select',
    'valuetype'   => 'text',
    'options'     => $editorList,
    'default'     => 'dhtmltextarea'
);

++$i;
$modversion['config'][$i] = array(
    'name'        => 'form_optionsuser',
    'title'       => '_MI_XOOPSTUBE_EDITORUSER',
    'description' => '_MI_XOOPSTUBE_EDITORCHOICEUSER',
    'formtype'    => 'select',
    'valuetype'   => 'text',
    'options'     => $editorList,
    'default'     => 'dhtmltextarea'
);
//                                'default'     => 'dhtml');
//                                'default'     => 'dhtmlext');

++$i;
$modversion['config'][$i]['name']        = 'screenshot';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_USESHOTS';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_USESHOTSDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
++$i;
$modversion['config'][$i]['name']        = 'usethumbs';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_USETHUMBS';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_USETHUMBSDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
++$i;
$modversion['config'][$i]['name']        = 'updatethumbs';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_IMGUPDATE';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_IMGUPDATEDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
++$i;
$modversion['config'][$i]['name']        = 'shotwidth';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_SHOTWIDTH';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_SHOTWIDTHDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 120;
++$i;
$modversion['config'][$i]['name']        = 'shotheight';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_SHOTHEIGHT';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_SHOTHEIGHTDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 90;
++$i;
$modversion['config'][$i]['name']        = 'maxfilesize';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_MAXFILESIZE';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_MAXFILESIZEDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 200000;
++$i;
$modversion['config'][$i]['name']        = 'maximgwidth';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_IMGWIDTH';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_IMGWIDTHDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 600;
++$i;
$modversion['config'][$i]['name']        = 'maximgheight';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_IMGHEIGHT';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_IMGHEIGHTDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 600;

// Directories -----------------------------------------------
++$i;
$modversion['config'][$i]['name']        = 'directiories';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_PREFERENCES_DIRECTIORIES';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype']    = 'line_break';
$modversion['config'][$i]['valuetype']   = 'textbox';
$modversion['config'][$i]['default']     = 'odd';

++$i;
$modversion['config'][$i]['name']        = 'dirmode';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_PREFERENCES_DIRMODE';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_PREFERENCES_DIRMODE_DESC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = '0777';
++$i;
$modversion['config'][$i]['name']        = 'mainimagedir';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_MAINIMGDIR';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_MAINIMGDIRDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'modules/' . $mydirname . '/assets/images';
++$i;
$modversion['config'][$i]['name']        = 'catimage';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_CATEGORYIMG';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_CATEGORYIMGDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
//$modversion['config'][$i]['default']     = 'uploads/xt_images/category';
$modversion['config'][$i]['default'] = 'uploads/xoopstube/category';
++$i;
$modversion['config'][$i]['name']        = 'videodir';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_VIDEODIR';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_VIDEODIRDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
//$modversion['config'][$i]['default']     = 'uploads/xt_images/videos';
$modversion['config'][$i]['default'] = 'uploads/xoopstube/videos';
++$i;
$modversion['config'][$i]['name']        = 'videoimgdir';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_VIDEOIMGDIR';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_VIDEOIMGDIRDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
//$modversion['config'][$i]['default']     = 'uploads/xt_images/screenshots';
$modversion['config'][$i]['default'] = 'uploads/xoopstube/screenshots';

// Other -------------------------------------------------
++$i;
$modversion['config'][$i]['name']        = 'other';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_PREFERENCES_OTHERS';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype']    = 'line_break';
$modversion['config'][$i]['valuetype']   = 'textbox';
$modversion['config'][$i]['default']     = 'odd';

++$i;
$modversion['config'][$i]['name']        = 'dateformat';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_DATEFORMAT';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_DATEFORMATDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'D, d-M-Y';
++$i;
$modversion['config'][$i]['name']        = 'dateformatadmin';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_DATEFORMATADMIN';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_DATEFORMATADMINDSC';
$modversion['config'][$i]['formtype']    = 'textbox';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']     = 'D, d-M-Y - G:i';
++$i;
$modversion['config'][$i]['name']        = 'totalchars';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_TOTALCHARS';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_TOTALCHARSDSC';
$modversion['config'][$i]['formtype']    = 'select';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 200;
$modversion['config'][$i]['options']     = array(
    '100' => 100,
    '200' => 200,
    '300' => 300,
    '400' => 400,
    '500' => 500,
    '750' => 750
);
++$i;
$modversion['config'][$i]['name']        = 'autoplay';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_AUTOPLAY';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_AUTOPLAYDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
++$i;
$modversion['config'][$i]['name']        = 'othervideos';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_OTHERVIDEOS';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_OTHERVIDEOSDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
++$i;
$modversion['config'][$i]['name']        = 'showsubmitter';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_SHOWSUBMITTER';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_SHOWSUBMITTERDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
++$i;
$modversion['config'][$i]['name']        = 'showsbookmarks';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_SHOWSBOOKMARKS';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_SHOWSBOOKMARKSDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
++$i;
$modversion['config'][$i]['name']        = 'usemetadescr';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_USEMETADESCR';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_USEMETADSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
++$i;
$modversion['config'][$i]['name']        = 'usercantag';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_USERTAGDESCR';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_USERTAGDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
++$i;
$modversion['config'][$i]['name']        = 'showrating';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_RATINGDISPLAY';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_RATINGDISPLAYDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
++$i;
$modversion['config'][$i]['name']        = 'showdisclaimer';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_SHOWDISCLAIMER';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_SHOWDISCLAIMERDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
++$i;
$modversion['config'][$i]['name']        = 'disclaimer';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_DISCLAIMER';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_DISCLAIMERDSC';
$modversion['config'][$i]['formtype']    = 'textsarea';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']
                                         = 'We have the right, but not the obligation to monitor and review submissions submitted by users, to this website. We shall not be responsible for any of the content of these messages. We further reserve the right, to delete, move or edit submissions that we, in its exclusive discretion, deems abusive, defamatory, obscene or in violation of any Copyright or Trademark laws or otherwise objectionable.';
++$i;
$modversion['config'][$i]['name']        = 'showvideodisclaimer';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_SHOWVIDEODISCL';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_SHOWVIDEODISCLDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 0;
++$i;
$modversion['config'][$i]['name']        = 'videodisclaimer';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_VIDEODISCLAIMER';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_VIDEODISCLAIMERDSC';
$modversion['config'][$i]['formtype']    = 'textsarea';
$modversion['config'][$i]['valuetype']   = 'text';
$modversion['config'][$i]['default']
                                         = 'The videos on this site are provided as is without warranty either expressed or implied. If you have a question concerning a particular piece video, feel free to contact the administrator of this website.<br /><br />Contact us if you have questions concerning this disclaimer.';
++$i;
$modversion['config'][$i]['name']        = 'copyright';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_COPYRIGHT';
$modversion['config'][$i]['description'] = '_MI_XOOPSTUBE_COPYRIGHTDSC';
$modversion['config'][$i]['formtype']    = 'yesno';
$modversion['config'][$i]['valuetype']   = 'int';
$modversion['config'][$i]['default']     = 1;
++$i;

// Notification ------------------------------------------
$modversion['config'][$i]['name']        = 'notifications';
$modversion['config'][$i]['title']       = '_MI_XOOPSTUBE_PREFERENCES_COMMENTS';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype']    = 'line_break';
$modversion['config'][$i]['valuetype']   = 'textbox';
$modversion['config'][$i]['default']     = 'odd';
++$i;
$modversion['hasNotification']             = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'xtubeNotifyIteminfo';

$modversion['notification']['category'][1]['name']           = 'global';
$modversion['notification']['category'][1]['title']          = _MI_XOOPSTUBE_GLOBAL_NOTIFY;
$modversion['notification']['category'][1]['description']    = _MI_XOOPSTUBE_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = array('index.php', 'viewcat.php', 'singlevideo.php');

$modversion['notification']['category'][2]['name']           = 'category';
$modversion['notification']['category'][2]['title']          = _MI_XOOPSTUBE_CATEGORY_NOTIFY;
$modversion['notification']['category'][2]['description']    = _MI_XOOPSTUBE_CATEGORY_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = array('viewcat.php', 'singlevideo.php');
$modversion['notification']['category'][2]['item_name']      = 'cid';
$modversion['notification']['category'][2]['allow_bookmark'] = 1;

$modversion['notification']['category'][3]['name']           = 'video';
$modversion['notification']['category'][3]['title']          = _MI_XOOPSTUBE_VIDEO_NOTIFY;
$modversion['notification']['category'][3]['description']    = _MI_XOOPSTUBE_FILE_NOTIFYDSC;
$modversion['notification']['category'][3]['subscribe_from'] = 'singlevideo.php';
$modversion['notification']['category'][3]['item_name']      = 'lid';
$modversion['notification']['category'][3]['allow_bookmark'] = 1;

$modversion['notification']['event'][1]['name']          = 'new_category';
$modversion['notification']['event'][1]['category']      = 'global';
$modversion['notification']['event'][1]['title']         = _MI_XOOPSTUBE_GLOBAL_NEWCATEGORY_NOTIFY;
$modversion['notification']['event'][1]['caption']       = _MI_XOOPSTUBE_GLOBAL_NEWCATEGORY_NOTIFYCAP;
$modversion['notification']['event'][1]['description']   = _MI_XOOPSTUBE_GLOBAL_NEWCATEGORY_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'global_newcategory_notify';
$modversion['notification']['event'][1]['mail_subject']  = _MI_XOOPSTUBE_GLOBAL_NEWCATEGORY_NOTIFYSBJ;

$modversion['notification']['event'][2]['name']          = 'video_modify';
$modversion['notification']['event'][2]['category']      = 'global';
$modversion['notification']['event'][2]['admin_only']    = 1;
$modversion['notification']['event'][2]['title']         = _MI_XOOPSTUBE_GLOBAL_VIDEOMODIFY_NOTIFY;
$modversion['notification']['event'][2]['caption']       = _MI_XOOPSTUBE_GLOBAL_VIDEOMODIFY_NOTIFYCAP;
$modversion['notification']['event'][2]['description']   = _MI_XOOPSTUBE_GLOBAL_VIDEOMODIFY_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'global_videomodify_notify';
$modversion['notification']['event'][2]['mail_subject']  = _MI_XOOPSTUBE_GLOBAL_VIDEOMODIFY_NOTIFYSBJ;

$modversion['notification']['event'][3]['name']          = 'video_broken';
$modversion['notification']['event'][3]['category']      = 'global';
$modversion['notification']['event'][3]['admin_only']    = 1;
$modversion['notification']['event'][3]['title']         = _MI_XOOPSTUBE_GLOBAL_VIDEOBROKEN_NOTIFY;
$modversion['notification']['event'][3]['caption']       = _MI_XOOPSTUBE_GLOBAL_VIDEOBROKEN_NOTIFYCAP;
$modversion['notification']['event'][3]['description']   = _MI_XOOPSTUBE_GLOBAL_VIDEOBROKEN_NOTIFYDSC;
$modversion['notification']['event'][3]['mail_template'] = 'global_videobroken_notify';
$modversion['notification']['event'][3]['mail_subject']  = _MI_XOOPSTUBE_GLOBAL_VIDEOBROKEN_NOTIFYSBJ;

$modversion['notification']['event'][4]['name']          = 'video_submit';
$modversion['notification']['event'][4]['category']      = 'global';
$modversion['notification']['event'][4]['admin_only']    = 1;
$modversion['notification']['event'][4]['title']         = _MI_XOOPSTUBE_GLOBAL_VIDEOSUBMIT_NOTIFY;
$modversion['notification']['event'][4]['caption']       = _MI_XOOPSTUBE_GLOBAL_VIDEOSUBMIT_NOTIFYCAP;
$modversion['notification']['event'][4]['description']   = _MI_XOOPSTUBE_GLOBAL_VIDEOSUBMIT_NOTIFYDSC;
$modversion['notification']['event'][4]['mail_template'] = 'global_videosubmit_notify';
$modversion['notification']['event'][4]['mail_subject']  = _MI_XOOPSTUBE_GLOBAL_VIDEOSUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][5]['name']          = 'new_video';
$modversion['notification']['event'][5]['category']      = 'global';
$modversion['notification']['event'][5]['title']         = _MI_XOOPSTUBE_GLOBAL_NEWVIDEO_NOTIFY;
$modversion['notification']['event'][5]['caption']       = _MI_XOOPSTUBE_GLOBAL_NEWVIDEO_NOTIFYCAP;
$modversion['notification']['event'][5]['description']   = _MI_XOOPSTUBE_GLOBAL_NEWVIDEO_NOTIFYDSC;
$modversion['notification']['event'][5]['mail_template'] = 'global_newfile_notify';
$modversion['notification']['event'][5]['mail_subject']  = _MI_XOOPSTUBE_GLOBAL_NEWVIDEO_NOTIFYSBJ;

$modversion['notification']['event'][6]['name']          = 'video_submit';
$modversion['notification']['event'][6]['category']      = 'category';
$modversion['notification']['event'][6]['admin_only']    = 1;
$modversion['notification']['event'][6]['title']         = _MI_XOOPSTUBE_CATEGORY_FILESUBMIT_NOTIFY;
$modversion['notification']['event'][6]['caption']       = _MI_XOOPSTUBE_CATEGORY_FILESUBMIT_NOTIFYCAP;
$modversion['notification']['event'][6]['description']   = _MI_XOOPSTUBE_CATEGORY_FILESUBMIT_NOTIFYDSC;
$modversion['notification']['event'][6]['mail_template'] = 'category_videosubmit_notify';
$modversion['notification']['event'][6]['mail_subject']  = _MI_XOOPSTUBE_CATEGORY_FILESUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][7]['name']          = 'new_video';
$modversion['notification']['event'][7]['category']      = 'category';
$modversion['notification']['event'][7]['title']         = _MI_XOOPSTUBE_CATEGORY_NEWVIDEO_NOTIFY;
$modversion['notification']['event'][7]['caption']       = _MI_XOOPSTUBE_CATEGORY_NEWVIDEO_NOTIFYCAP;
$modversion['notification']['event'][7]['description']   = _MI_XOOPSTUBE_CATEGORY_NEWVIDEO_NOTIFYDSC;
$modversion['notification']['event'][7]['mail_template'] = 'category_newfile_notify';
$modversion['notification']['event'][7]['mail_subject']  = _MI_XOOPSTUBE_CATEGORY_NEWVIDEO_NOTIFYSBJ;

$modversion['notification']['event'][8]['name']          = 'approve';
$modversion['notification']['event'][8]['category']      = 'video';
$modversion['notification']['event'][8]['invisible']     = 1;
$modversion['notification']['event'][8]['title']         = _MI_XOOPSTUBE_VIDEO_APPROVE_NOTIFY;
$modversion['notification']['event'][8]['caption']       = _MI_XOOPSTUBE_VIDEO_APPROVE_NOTIFYCAP;
$modversion['notification']['event'][8]['description']   = _MI_XOOPSTUBE_VIDEO_APPROVE_NOTIFYDSC;
$modversion['notification']['event'][8]['mail_template'] = 'video_approve_notify';
$modversion['notification']['event'][8]['mail_subject']  = _MI_XOOPSTUBE_VIDEO_APPROVE_NOTIFYSBJ;

// On Update
//if (!empty($_POST['fct']) && !empty($_POST['op']) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok'
//    && $_POST['dirname'] == $modversion['dirname']
//) {
//    include __DIR__ . '/include/onupdate.inc.php';
//}
